env: local
db:
  host: localhost
  port: 5432
  user: dbOwner
  password: kasdjom
  dbname: url_shortener
http_server:
 address: localhost:8080
 timeout: 4s
 idle_timeout: 60s
 user: Owner
 password: Owner1923
 